---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: lula-test
  namespace: foo
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: lula-test
  namespace: test
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: lula-test
  namespace: test1
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: lula-test
  namespace: test2
spec:
  mtls:
    mode: STRICT
