---
apiVersion: v1
kind: Pod
metadata:
  name: nonroot
  namespace: demo
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: root
      securityContext:
        runAsNonRoot: true
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
