name: E2E Testing

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup golang
      uses: ./.github/actions/golang

    - name: Display Go version
      run: go version

    - name: Build CLI
      run: |
        make build
    
    - name: Make lula executable
      run: |
        chmod +x bin/lula
      
    - name: e2e Tests
      run: |
        make test
